qca-swiss-army-knife: use /usr/bin/env python3
bitbake world shows this issue:

ERROR: nativesdk-qca-swiss-army-knife-0.0+-r0 do_package_qa: QA Issue:
/usr/local/oe-sdk-hardcoded-buildpath/sysroots/x86_64-qcomsdk-linux/usr/bin/read-powers
contained in package nativesdk-qca-swiss-army-knife requires
/usr/bin/python3, but no providers found in
RDEPENDS:nativesdk-qca-swiss-army-knife? [file-rdeps]

python is not provided in the SDK, by design, and
nativesdk-sdk-provides-dummy exists to fake such things. However a
better solution is to actually use /usr/bin/env python3, regardless of
this issue. With this patch the QA issue is obviously not there.

Signed-off-by: Nicolas Dechesne <nicolas.dechesne@oss.qualcomm.com>